server:
  port: 8080
  session:
    timeout: 1800
  #address: acount.yayao8.com
  tomcat:
    max-threads: 1000
    min-spare-threads: 200
    accept-count: 1000
    max-connections: 1000
 # connection-timeout: 60 
spring:
   datasource:
     name: master
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://118.190.133.146:3306/yayao_app_center_db
     username: root
     password: liliu
   redis:
     host: 118.190.133.146
     password: liliu
     port: 6379 
     database: 1
     timeout: 3000
     pool: 
       min-idle: 100
       max-idle: 300
       max-active: 800 
myPugin: 
  session: 
    myDomainName: jiehao9.com
  projectName: YaYaoAppCenter
  requestAuth: requestAuthProd